module.exports = {
  extends: [
    'codelyzer'
  ],

  rules: {
    'angular-whitespace': false, // deprecated
    'prefer-on-push-component-change-detection': false,
    'component-class-suffix': true,
    'component-max-inline-declarations': true,
    'component-selector': [true, 'element', 'sg', 'kebab-case'],
    'contextual-lifecycle': true,
    'directive-class-suffix': true,
    'directive-selector': [true, 'attribute', 'sg', 'camelCase'],
    'no-attribute-decorator': true,
    'no-conflicting-lifecycle': true,
    'no-forward-ref': true,
    'no-host-metadata-property': true,
    'no-input-rename': true,
    'no-inputs-metadata-property': true,
    'no-lifecycle-call': true,
    'no-output-native': true,
    'no-output-on-prefix': true,
    'no-output-rename': true,
    'no-outputs-metadata-property': true,
    'no-pipe-impure': true,
    'no-queries-metadata-property': true,
    'no-unused-css': true,
    'pipe-naming': false, // deprecated
    'pipe-prefix': false,
    'prefer-inline-decorator': false,
    'prefer-output-readonly': true,
    'relative-url-prefix': true,
    'template-accessibility-alt-text': true,
    'template-accessibility-elements-content': true,
    'template-accessibility-label-for': true,
    'template-accessibility-tabindex-no-positive': true,
    'template-accessibility-table-scope': true,
    'template-accessibility-valid-aria': true,
    'template-banana-in-box': true,
    'template-click-events-have-key-events': true,
    'template-conditional-complexity': [true, 4],
    'template-cyclomatic-complexity': [true, 5],
    'template-i18n': [true, 'check-id', 'check-text'],
    'template-mouse-events-have-key-events': true,
    'template-no-any': true,
    'template-no-autofocus': true,
    'template-no-distracting-elements': true,
    'template-no-negated-async': true,
    'template-use-track-by-function': true,
    'use-component-selector': true,
    'use-component-view-encapsulation': true,
    'use-lifecycle-interface': true,
    'use-pipe-decorator': true,
    'use-pipe-transform-interface': true
  }
}
